### PR TITLE
Meteor 2.3 & @apollo/client 3.7.12

### PR DESCRIPTION
**Pull request by StorytellerCZ**

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@filipenevola please merge this. The travis failure is due to spacejam, we will need a new test suite here.

**Comment by StorytellerCZ** [comment]
@Grubba27 can you please check and publish?

**Comment by Grubba27** [comment]
if it is okay I will release.

**Comment by Grubba27** [comment]
published under the 4.2 namespace! 
the 4.10 was already launched as you can see here https://packosphere.com/meteor/apollo

**Pull request merged**
